openapi: 3.1.0
info:
  title: Nussknacker Designer API
  version: ''
paths:
  /api/components/{id}/usages:
    get:
      tags:
      - Components
      summary: Show component usage
      operationId: getApiComponentsIdUsages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComponentUsagesInScenario'
              examples:
                Example0:
                  summary: List component usages
                  value:
                  - name: scenario1
                    nodesUsagesData:
                    - nodeId: csv-source
                      type: ScenarioUsageData
                    isFragment: false
                    processCategory: Category1
                    modificationDate: '2023-11-29T08:54:22.520866Z'
                    modifiedAt: '2023-11-29T08:54:22.520866Z'
                    modifiedBy: admin
                    createdAt: '2023-11-14T11:09:28.078800Z'
                    createdBy: admin
                    lastAction:
                      id: 45c0f3f5-3ef7-4dc2-92d4-8bb826ec0ca9
                      processId: 1
                      processVersionId: 1
                      user: admin
                      createdAt: '2023-11-29T08:54:22.520866Z'
                      performedAt: '2023-11-29T08:54:22.520866Z'
                      actionType: DEPLOY
                      state: FINISHED
                      buildInfo: {}
                Example1:
                  summary: List component usages with no last Action
                  value:
                  - name: scenario1
                    nodesUsagesData:
                    - nodeId: csv-source
                      type: ScenarioUsageData
                    isFragment: false
                    processCategory: Category1
                    modificationDate: '2023-11-29T08:54:22.520866Z'
                    modifiedAt: '2023-11-29T08:54:22.520866Z'
                    modifiedBy: admin
                    createdAt: '2023-11-14T11:09:28.078800Z'
                    createdBy: admin
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              example: Component {id} not exist.
      security:
      - httpAuth: []
  /api/components:
    get:
      tags:
      - Components
      summary: Listing components
      operationId: getApiComponents
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComponentListElement'
              examples:
                Example:
                  summary: List of available components
                  value:
                  - id: request-response-embedded-customnode-collect
                    name: collect
                    icon: /assets/components/CustomNode.svg
                    componentType: custom
                    componentGroupName: custom
                    categories:
                    - RequestResponse
                    links:
                    - id: documentation
                      title: Documentation
                      icon: /assets/icons/documentation.svg
                      url: https://nussknacker.io/documentation/docs/scenarios_authoring/RRDataSourcesAndSinks/#collect
                    usageCount: 2
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
      security:
      - httpAuth: []
  /api/app/healthCheck:
    get:
      tags:
      - App
      summary: Application health check service
      operationId: getApiAppHealthcheck
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckProcessSuccessResponseDto'
              examples:
                Example:
                  summary: Application is healthy
                  value:
                    status: OK
  /api/app/buildInfo:
    get:
      tags:
      - App
      summary: Application info service
      operationId: getApiAppBuildinfo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildInfoDto'
              examples:
                Example:
                  summary: Application build info response
                  value:
                    name: nussknacker
                    version: 1.234.0
                    buildTime: '2023-09-25T09:26:30.402299'
                    gitCommit: d4e42ee5c594ffe70a37faca3579eb535dac9820
                    processingType:
                      streaming:
                        process-version: '0.1'
                        engine-version: '0.2'
                        generation-time: '2023-09-25T09:26:30.402299'
  /api/app/healthCheck/process/deployment:
    get:
      tags:
      - App
      summary: Deployed processes health check service
      operationId: getApiAppHealthcheckProcessDeployment
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckProcessSuccessResponseDto'
              examples:
                Example:
                  summary: All deployed processes are healthy
                  value:
                    status: OK
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckProcessErrorResponseDto'
              examples:
                Example:
                  summary: Some processes are unhealthy
                  value:
                    status: ERROR
                    message: Scenarios with status PROBLEM
                    processes:
                    - process1
                    - process2
      security:
      - httpAuth: []
  /api/app/healthCheck/process/validation:
    get:
      tags:
      - App
      summary: Deployed processes validation service
      operationId: getApiAppHealthcheckProcessValidation
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckProcessSuccessResponseDto'
              examples:
                Example:
                  summary: There are no validation errors among the processes
                  value:
                    status: OK
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '500':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckProcessErrorResponseDto'
              examples:
                Example:
                  summary: Some processes have validation errors
                  value:
                    status: ERROR
                    message: Scenarios with validation errors
                    processes:
                    - process2
                    - process3
      security:
      - httpAuth: []
  /api/app/processingtype/reload:
    post:
      tags:
      - App
      summary: Processing type data reload service
      operationId: postApiAppProcessingtypeReload
      responses:
        '204':
          description: ''
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
      security:
      - httpAuth: []
  /api/app/config:
    get:
      tags:
      - App
      summary: Server configuration viewer service
      operationId: getApiAppConfig
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
              examples:
                Example:
                  summary: Server configuration response
                  value:
                    environment: local
                    scenarioTypes:
                      development-tests:
                        type: development-tests
                      modelConfig:
                        classPath:
                        - model/devModel.jar
                        - model/flinkExecutor.jar
                        - components/flink
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
      security:
      - httpAuth: []
  /api/app/config/categoriesWithProcessingType:
    get:
      tags:
      - App
      summary: Configured categories with their processing types service
      operationId: getApiAppConfigCategorieswithprocessingtype
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Map_String'
              examples:
                Example:
                  summary: Configured categories and their processing types
                  value:
                    Category1: streaming
                    Category2: streaming2
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
      security:
      - httpAuth: []
  /api/nodes/{processName}/additionalInfo:
    post:
      tags:
      - Nodes
      summary: Additional info for provided node
      operationId: postApiNodesProcessnameAdditionalinfo
      parameters:
      - name: processName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodeData'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdditionalInfo'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      security:
      - httpAuth: []
  /api/nodes/{processName}/validation:
    post:
      tags:
      - Nodes
      summary: Validate provided Node
      operationId: postApiNodesProcessnameValidation
      parameters:
      - name: processName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodeValidationRequestDto'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeValidationResultDto'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      security:
      - httpAuth: []
  /api/parameters/{processingType}/suggestions:
    post:
      tags:
      - Nodes
      summary: Suggest possible variables
      operationId: postApiParametersProcessingtypeSuggestions
      parameters:
      - name: processingType
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpressionSuggestionRequestDto'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExpressionSuggestionDto'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      security:
      - httpAuth: []
  /api/parameters/{processingType}/validate:
    post:
      tags:
      - Nodes
      summary: Validate node parameters
      operationId: postApiParametersProcessingtypeValidate
      parameters:
      - name: processingType
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametersValidationRequestDto'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParametersValidationResultDto'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      security:
      - httpAuth: []
  /api/properties/{processName}/additionalInfo:
    post:
      tags:
      - Nodes
      summary: Additional info for provided properties
      operationId: postApiPropertiesProcessnameAdditionalinfo
      parameters:
      - name: processName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessProperties'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdditionalInfo'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      security:
      - httpAuth: []
  /api/properties/{processName}/validation:
    post:
      tags:
      - Nodes
      summary: Validate node properties
      operationId: postApiPropertiesProcessnameValidation
      parameters:
      - name: processName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PropertiesValidationRequestDto'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeValidationResultDto'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
      security:
      - httpAuth: []
  /api/notifications:
    get:
      tags:
      - Notifications
      summary: Endpoint to display notifications
      operationId: getApiNotifications
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
              examples:
                Example:
                  summary: Display simple deployment notification
                  value:
                  - id: 0351c45a-2c4c-4ffd-8848-ae6c2f281ef1
                    scenarioName: scenario1
                    message: Deployment finished
                    toRefresh:
                    - versions
                    - activity
                    - state
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
      security:
      - httpAuth: []
  /api/user:
    get:
      tags:
      - User
      summary: Logged user info service
      operationId: getApiUser
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisplayableUser'
              examples:
                Example0:
                  summary: Common user info
                  value:
                    id: reader
                    username: reader
                    isAdmin: false
                    categories:
                    - Category1
                    categoryPermissions:
                      Category1:
                      - Read
                    globalPermissions: []
                Example1:
                  summary: Admin user info
                  value:
                    id: admin
                    username: admin
                    isAdmin: true
                    categories:
                    - Category1
                    - Category2
                    categoryPermissions: {}
                    globalPermissions: []
        '401':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authentication failed
                  value: The supplied authentication is invalid
        '403':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: Authorization failed
                  value: The supplied authentication is not authorized to access this
                    resource
      security:
      - httpAuth: []
components:
  schemas:
    AdditionalInfo:
      oneOf:
      - $ref: '#/components/schemas/MarkdownAdditionalInfo'
    BranchEndData:
      required:
      - definition
      type: object
      properties:
        definition:
          $ref: '#/components/schemas/BranchEndDefinition'
    BranchEndDefinition:
      required:
      - id
      - joinId
      type: object
      properties:
        id:
          type: string
        joinId:
          type: string
    BranchParameters:
      required:
      - branchId
      type: object
      properties:
        branchId:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
    BuildInfoDto:
      required:
      - name
      - gitCommit
      - buildTime
      - version
      - processingType
      type: object
      properties:
        name:
          type: string
        gitCommit:
          type: string
        buildTime:
          type: string
        version:
          type: string
        processingType:
          $ref: '#/components/schemas/Map_Map_String_String'
        globalBuildInfo:
          $ref: '#/components/schemas/Map_String'
    CaretPosition2d:
      required:
      - row
      - column
      type: object
      properties:
        row:
          type: integer
          format: int32
        column:
          type: integer
          format: int32
    ComponentGroupName:
      required:
      - value
      type: object
      properties:
        value:
          type: string
    ComponentLink:
      required:
      - id
      - title
      - icon
      - url
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        icon:
          type: string
        url:
          type: string
    ComponentListElement:
      required:
      - id
      - name
      - icon
      - componentType
      - componentGroupName
      - usageCount
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        icon:
          type: string
        componentType:
          $ref: '#/components/schemas/ComponentType'
        componentGroupName:
          $ref: '#/components/schemas/ComponentGroupName'
        categories:
          type: array
          items:
            type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/ComponentLink'
        usageCount:
          type: integer
          format: int64
    ComponentType:
      type: string
      enum:
      - source
      - sink
      - service
      - custom
      - fragment
      - builtin
    ComponentUsagesInScenario:
      required:
      - name
      - isFragment
      - processCategory
      - modificationDate
      - modifiedAt
      - modifiedBy
      - createdAt
      - createdBy
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ProcessName'
        nodesUsagesData:
          type: array
          items:
            $ref: '#/components/schemas/NodeUsageData'
        isFragment:
          type: boolean
        processCategory:
          type: string
        modificationDate:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        lastAction:
          $ref: '#/components/schemas/ProcessAction'
    CustomNode:
      required:
      - id
      - nodeType
      type: object
      properties:
        id:
          type: string
        outputVar:
          type:
          - string
          - 'null'
        nodeType:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    DataToRefresh:
      type: string
      enum:
      - versions
      - activity
      - state
    DisplayableUser:
      required:
      - id
      - username
      - isAdmin
      - categoryPermissions
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        isAdmin:
          type: boolean
        categories:
          type: array
          items:
            type: string
        categoryPermissions:
          $ref: '#/components/schemas/Map_List_String'
        globalPermissions:
          type: array
          items:
            type: string
    Edge:
      required:
      - from
      - to
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        edgeType:
          $ref: '#/components/schemas/EdgeType'
    EdgeType:
      oneOf:
      - $ref: '#/components/schemas/FilterFalse'
      - $ref: '#/components/schemas/FilterTrue'
      - $ref: '#/components/schemas/FragmentOutput'
      - $ref: '#/components/schemas/NextSwitch'
      - $ref: '#/components/schemas/SwitchDefault'
    Enricher:
      required:
      - id
      - service
      - output
      type: object
      properties:
        id:
          type: string
        service:
          $ref: '#/components/schemas/ServiceRef'
        output:
          type: string
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    Expression:
      required:
      - language
      - expression
      type: object
      properties:
        language:
          type: string
        expression:
          type: string
    ExpressionSuggestionDto:
      required:
      - methodName
      - refClazz
      - fromClass
      type: object
      properties:
        methodName:
          type: string
        refClazz: {}
        fromClass:
          type: boolean
        description:
          type:
          - string
          - 'null'
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ParameterDto'
    ExpressionSuggestionRequestDto:
      required:
      - expression
      - caretPosition2d
      - variableTypes
      type: object
      properties:
        expression:
          $ref: '#/components/schemas/Expression'
        caretPosition2d:
          $ref: '#/components/schemas/CaretPosition2d'
        variableTypes:
          $ref: '#/components/schemas/Map_TypingResultDto'
    Field:
      required:
      - name
      - expression
      type: object
      properties:
        name:
          type: string
        expression:
          $ref: '#/components/schemas/Expression'
    Filter:
      required:
      - id
      - expression
      type: object
      properties:
        id:
          type: string
        expression:
          $ref: '#/components/schemas/Expression'
        isDisabled:
          type:
          - boolean
          - 'null'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    FilterFalse:
      type: object
    FilterTrue:
      type: object
    FixedExpressionValue:
      required:
      - expression
      - label
      type: object
      properties:
        expression:
          type: string
        label:
          type: string
    FragmentClazzRef:
      required:
      - refClazzName
      type: object
      properties:
        refClazzName:
          type: string
    FragmentInput:
      required:
      - id
      - ref
      type: object
      properties:
        id:
          type: string
        ref:
          $ref: '#/components/schemas/FragmentRef'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
        isDisabled:
          type:
          - boolean
          - 'null'
        fragmentParams:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/FragmentParameter'
    FragmentInputDefinition:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/FragmentParameter'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    FragmentOutput:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    FragmentOutputDefinition:
      required:
      - id
      - outputName
      type: object
      properties:
        id:
          type: string
        outputName:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    FragmentOutputVarDefinition:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
    FragmentParameter:
      required:
      - name
      - typ
      - required
      type: object
      properties:
        name:
          type: string
        typ:
          $ref: '#/components/schemas/FragmentClazzRef'
        required:
          type: boolean
        initialValue:
          $ref: '#/components/schemas/FixedExpressionValue'
        hintText:
          type:
          - string
          - 'null'
        valueEditor:
          $ref: '#/components/schemas/ValueInputWithFixedValues'
        valueCompileTimeValidation:
          $ref: '#/components/schemas/ParameterValueCompileTimeValidation'
    FragmentRef:
      required:
      - id
      - outputVariableNames
      type: object
      properties:
        id:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
        outputVariableNames:
          $ref: '#/components/schemas/Map_String'
    FragmentUsageData:
      required:
      - fragmentNodeId
      - nodeId
      type: object
      properties:
        fragmentNodeId:
          type: string
        nodeId:
          type: string
    FragmentUsageOutput:
      required:
      - id
      - outputName
      type: object
      properties:
        id:
          type: string
        outputName:
          type: string
        outputVar:
          $ref: '#/components/schemas/FragmentOutputVarDefinition'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    HealthCheckProcessErrorResponseDto:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status1'
        message:
          type:
          - string
          - 'null'
        processes:
          type:
          - array
          - 'null'
          items:
            type: string
    HealthCheckProcessSuccessResponseDto:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
        message:
          type:
          - string
          - 'null'
        processes:
          type:
          - array
          - 'null'
          items:
            type: string
    Join:
      required:
      - id
      - nodeType
      type: object
      properties:
        id:
          type: string
        outputVar:
          type:
          - string
          - 'null'
        nodeType:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
        branchParameters:
          type: array
          items:
            $ref: '#/components/schemas/BranchParameters'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    LayoutData:
      required:
      - x
      - y
      type: object
      properties:
        x:
          type: integer
          format: int64
        y:
          type: integer
          format: int64
    Map_List_String:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    Map_Map_String_String:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Map_String'
    Map_Map_String_TypingResultDto:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Map_TypingResultDto'
    Map_String:
      type: object
      additionalProperties:
        type: string
    Map_TypingResultDto:
      type: object
      additionalProperties: {}
    MarkdownAdditionalInfo:
      required:
      - content
      type: object
      properties:
        content:
          type: string
    NextSwitch:
      required:
      - condition
      type: object
      properties:
        condition:
          $ref: '#/components/schemas/Expression'
    NodeData:
      oneOf:
      - $ref: '#/components/schemas/BranchEndData'
      - $ref: '#/components/schemas/CustomNode'
      - $ref: '#/components/schemas/Enricher'
      - $ref: '#/components/schemas/Filter'
      - $ref: '#/components/schemas/FragmentInput'
      - $ref: '#/components/schemas/FragmentInputDefinition'
      - $ref: '#/components/schemas/FragmentOutputDefinition'
      - $ref: '#/components/schemas/FragmentUsageOutput'
      - $ref: '#/components/schemas/Join'
      - $ref: '#/components/schemas/Processor'
      - $ref: '#/components/schemas/Sink'
      - $ref: '#/components/schemas/Source'
      - $ref: '#/components/schemas/Split'
      - $ref: '#/components/schemas/Switch'
      - $ref: '#/components/schemas/Variable'
      - $ref: '#/components/schemas/VariableBuilder'
    NodeUsageData:
      oneOf:
      - $ref: '#/components/schemas/FragmentUsageData'
      - $ref: '#/components/schemas/ScenarioUsageData'
    NodeValidationError:
      required:
      - typ
      - message
      - description
      - errorType
      type: object
      properties:
        typ:
          type: string
        message:
          type: string
        description:
          type: string
        fieldName:
          type:
          - string
          - 'null'
        errorType:
          $ref: '#/components/schemas/NodeValidationErrorType'
    NodeValidationErrorType:
      type: string
      enum:
      - RenderNotAllowed
      - SaveNotAllowed
      - SaveAllowed
    NodeValidationRequestDto:
      required:
      - nodeData
      - processProperties
      - variableTypes
      type: object
      properties:
        nodeData:
          type: object
        processProperties: {}
        variableTypes:
          $ref: '#/components/schemas/Map_TypingResultDto'
        branchVariableTypes:
          $ref: '#/components/schemas/Map_Map_String_TypingResultDto'
        outgoingEdges:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Edge'
    NodeValidationResultDto:
      required:
      - validationPerformed
      type: object
      properties:
        parameters:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/UIParameterDto'
        expressionType: {}
        validationErrors:
          type: array
          items:
            $ref: '#/components/schemas/NodeValidationError'
        validationPerformed:
          type: boolean
    Notification:
      required:
      - id
      - message
      type: object
      properties:
        id:
          type: string
        scenarioName:
          type:
          - string
          - 'null'
        message:
          type: string
        type:
          $ref: '#/components/schemas/NotificationType'
        toRefresh:
          type: array
          items:
            $ref: '#/components/schemas/DataToRefresh'
    NotificationType:
      type: string
      enum:
      - info
      - success
      - error
    Parameter:
      required:
      - name
      - expression
      type: object
      properties:
        name:
          type: string
        expression:
          $ref: '#/components/schemas/Expression'
    ParameterDto:
      required:
      - name
      - refClazz
      type: object
      properties:
        name:
          type: string
        refClazz: {}
    ParameterValueCompileTimeValidation:
      required:
      - validationExpression
      type: object
      properties:
        validationExpression:
          $ref: '#/components/schemas/Expression'
        validationFailedMessage:
          type:
          - string
          - 'null'
    ParametersValidationRequestDto:
      required:
      - variableTypes
      type: object
      properties:
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/UIValueParameterDto'
        variableTypes:
          $ref: '#/components/schemas/Map_TypingResultDto'
    ParametersValidationResultDto:
      required:
      - validationPerformed
      type: object
      properties:
        validationErrors:
          type: array
          items:
            $ref: '#/components/schemas/NodeValidationError'
        validationPerformed:
          type: boolean
    ProcessAction:
      required:
      - id
      - processId
      - processVersionId
      - user
      - createdAt
      - performedAt
      - actionType
      - state
      - buildInfo
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ProcessActionId'
        processId:
          $ref: '#/components/schemas/ProcessId'
        processVersionId:
          $ref: '#/components/schemas/VersionId'
        user:
          type: string
        createdAt:
          type: string
          format: date-time
        performedAt:
          type: string
          format: date-time
        actionType:
          $ref: '#/components/schemas/ProcessActionType'
        state:
          $ref: '#/components/schemas/ProcessActionState'
        failureMessage:
          type:
          - string
          - 'null'
        commentId:
          type:
          - integer
          - 'null'
          format: int64
        comment:
          type:
          - string
          - 'null'
        buildInfo:
          $ref: '#/components/schemas/Map_String'
    ProcessActionId:
      required:
      - value
      type: object
      properties:
        value:
          type: string
          format: uuid
    ProcessActionState:
      type: string
      enum:
      - IN_PROGRESS
      - FINISHED
      - FAILED
      - EXECUTION_FINISHED
    ProcessActionType:
      type: string
      enum:
      - DEPLOY
      - CANCEL
      - ARCHIVE
      - UNARCHIVE
      - PAUSE
      - RENAME
    ProcessAdditionalFields:
      required:
      - properties
      - metaDataType
      type: object
      properties:
        description:
          type:
          - string
          - 'null'
        properties:
          $ref: '#/components/schemas/Map_String'
        metaDataType:
          type: string
    ProcessId:
      required:
      - value
      type: object
      properties:
        value:
          type: integer
          format: int64
    ProcessName:
      required:
      - value
      type: object
      properties:
        value:
          type: string
    ProcessProperties:
      required:
      - additionalFields
      type: object
      properties:
        additionalFields:
          $ref: '#/components/schemas/ProcessAdditionalFields'
    Processor:
      required:
      - id
      - service
      type: object
      properties:
        id:
          type: string
        service:
          $ref: '#/components/schemas/ServiceRef'
        isDisabled:
          type:
          - boolean
          - 'null'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    PropertiesValidationRequestDto:
      required:
      - additionalFields
      - name
      type: object
      properties:
        additionalFields:
          $ref: '#/components/schemas/ProcessAdditionalFields'
        name:
          $ref: '#/components/schemas/ProcessName'
    ScenarioUsageData:
      required:
      - nodeId
      type: object
      properties:
        nodeId:
          type: string
    ServiceRef:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
    Sink:
      required:
      - id
      - ref
      type: object
      properties:
        id:
          type: string
        ref:
          $ref: '#/components/schemas/SinkRef'
        legacyEndResultExpression:
          $ref: '#/components/schemas/Expression'
        isDisabled:
          type:
          - boolean
          - 'null'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    SinkRef:
      required:
      - typ
      type: object
      properties:
        typ:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
    Source:
      required:
      - id
      - ref
      type: object
      properties:
        id:
          type: string
        ref:
          $ref: '#/components/schemas/SourceRef'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    SourceRef:
      required:
      - typ
      type: object
      properties:
        typ:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
    Split:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    Status:
      type: string
      enum:
      - OK
    Status1:
      type: string
      enum:
      - ERROR
    Switch:
      required:
      - id
      type: object
      properties:
        id:
          type: string
        expression:
          $ref: '#/components/schemas/Expression'
        exprVal:
          type:
          - string
          - 'null'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    SwitchDefault:
      type: object
    UIParameterDto:
      required:
      - name
      - typ
      - editor
      - defaultValue
      - additionalVariables
      - branchParam
      - label
      type: object
      properties:
        name:
          type: string
        typ: {}
        editor:
          type: object
        defaultValue:
          $ref: '#/components/schemas/Expression'
        additionalVariables:
          $ref: '#/components/schemas/Map_TypingResultDto'
        variablesToHide:
          type: array
          items:
            type: string
        branchParam:
          type: boolean
        hintText:
          type:
          - string
          - 'null'
        label:
          type: string
    UIValueParameterDto:
      required:
      - name
      - typ
      - expression
      type: object
      properties:
        name:
          type: string
        typ: {}
        expression:
          $ref: '#/components/schemas/Expression'
    UserDefinedAdditionalNodeFields:
      type: object
      properties:
        description:
          type:
          - string
          - 'null'
        layoutData:
          $ref: '#/components/schemas/LayoutData'
    ValueInputWithFixedValues:
      oneOf:
      - $ref: '#/components/schemas/ValueInputWithFixedValuesProvided'
    ValueInputWithFixedValuesProvided:
      required:
      - allowOtherValue
      type: object
      properties:
        fixedValuesList:
          type: array
          items:
            $ref: '#/components/schemas/FixedExpressionValue'
        allowOtherValue:
          type: boolean
    Variable:
      required:
      - id
      - varName
      - value
      type: object
      properties:
        id:
          type: string
        varName:
          type: string
        value:
          $ref: '#/components/schemas/Expression'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    VariableBuilder:
      required:
      - id
      - varName
      type: object
      properties:
        id:
          type: string
        varName:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        additionalFields:
          $ref: '#/components/schemas/UserDefinedAdditionalNodeFields'
    VersionId:
      required:
      - value
      type: object
      properties:
        value:
          type: integer
          format: int64
  securitySchemes:
    httpAuth:
      type: http
      scheme: basic
