openapi: 3.1.0
info:
  title: Nussknacker Scenario Activity API
  version: 1.1.0
paths:
  /api/processes/{scenarioName}/activity:
    get:
      tags:
      - Activities
      summary: Scenario activity service
      operationId: getApiProcessesScenarionameActivity
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioCommentsAndAttachments'
              examples:
                Example:
                  summary: Display scenario activity
                  value:
                    comments:
                    - id: 1
                      processVersionId: 1
                      content: some comment
                      user: test
                      createDate: '2024-01-17T14:21:17Z'
                    attachments:
                    - id: 1
                      processVersionId: 1
                      fileName: some_file.txt
                      user: test
                      createDate: '2024-01-17T14:21:17Z'
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
      deprecated: true
  /api/processes/{scenarioName}/activity/activities/count:
    get:
      tags:
      - Activities
      summary: Scenario activities count service
      operationId: getApiProcessesScenarionameActivityActivitiesCount
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: activityType
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioActivitiesCount'
              example:
                fullCount: 123
        '400':
          description: 'Invalid value for: query parameter activityType'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
  /api/processes/{scenarioName}/activity/activities/search:
    get:
      tags:
      - Activities
      summary: Scenario activities count service
      operationId: getApiProcessesScenarionameActivityActivitiesSearch
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: searchText
        in: query
        required: true
        schema:
          type: string
      - name: activityType
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioActivitiesSearchResult'
              examples:
                Example:
                  summary: Result of activities full-text search
                  value:
                    foundActivities:
                    - id: f640f359-64b8-47cc-80a3-c48c266dc070
                      index: 101
                    - id: 14f4f954-6d66-4a5a-87b1-afa543cff9c5
                      index: 498
        '400':
          description: 'Invalid value for: query parameter searchText, Invalid value
            for: query parameter activityType'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
  /api/processes/{scenarioName}/activity/activities/metadata:
    get:
      tags:
      - Activities
      summary: Scenario activities metadata service
      operationId: getApiProcessesScenarionameActivityActivitiesMetadata
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioActivitiesMetadata'
              example:
                activities:
                - type: SCENARIO_CREATED
                  displayableName: Scenario created
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: SCENARIO_ARCHIVED
                  displayableName: Scenario archived
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: SCENARIO_UNARCHIVED
                  displayableName: Scenario unarchived
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: SCENARIO_DEPLOYED
                  displayableName: Deployment
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: SCENARIO_CANCELED
                  displayableName: Cancel
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: SCENARIO_MODIFIED
                  displayableName: New version saved
                  icon: /assets/states/error.svg
                  supportedActions:
                  - compare
                - type: SCENARIO_NAME_CHANGED
                  displayableName: Scenario name changed
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: COMMENT_ADDED
                  displayableName: Comment
                  icon: /assets/states/error.svg
                  supportedActions:
                  - delete_comment
                  - edit_comment
                - type: ATTACHMENT_ADDED
                  displayableName: Attachment
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: CHANGED_PROCESSING_MODE
                  displayableName: Processing mode change
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: INCOMING_MIGRATION
                  displayableName: Incoming migration
                  icon: /assets/states/error.svg
                  supportedActions:
                  - compare
                - type: OUTGOING_MIGRATION
                  displayableName: Outgoing migration
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: PERFORMED_SINGLE_EXECUTION
                  displayableName: Processing data
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: PERFORMED_SCHEDULED_EXECUTION
                  displayableName: Processing data
                  icon: /assets/states/error.svg
                  supportedActions: []
                - type: AUTOMATIC_UPDATE
                  displayableName: Automatic update
                  icon: /assets/states/error.svg
                  supportedActions:
                  - compare
                actions:
                - id: compare
                  displayableName: Compare
                  icon: /assets/states/error.svg
                - id: delete_comment
                  displayableName: Delete
                  icon: /assets/states/error.svg
                - id: edit_comment
                  displayableName: Edit
                  icon: /assets/states/error.svg
                - id: download_attachment
                  displayableName: Download
                  icon: /assets/states/error.svg
                - id: delete_attachment
                  displayableName: Delete
                  icon: /assets/states/error.svg
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
  /api/processes/{scenarioName}/activity/activities:
    get:
      tags:
      - Activities
      summary: Scenario activities service
      operationId: getApiProcessesScenarionameActivityActivities
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: pageSize
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: pageNumber
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: activityType
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioActivities'
              examples:
                Example:
                  summary: Display scenario actions
                  value:
                    activities:
                    - id: 33e5143e-187d-455e-99ec-56f607729c98
                      type: SCENARIO_CREATED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields: []
                    - id: 4677ad89-154a-424d-b1d3-26632b0b6b8a
                      type: SCENARIO_ARCHIVED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields: []
                    - id: aa4b30a8-9051-4a2a-ae6e-7042210ae096
                      type: SCENARIO_UNARCHIVED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields: []
                    - id: 10b5f550-eaef-419d-8264-219dca9a84c5
                      type: SCENARIO_DEPLOYED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      comment: Deployment of scenario - task JIRA-1234
                      additionalFields: []
                    - id: d3381b4d-220e-459e-bedd-71b142c257a7
                      type: SCENARIO_CANCELED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      comment: Canceled because marketing campaign ended
                      additionalFields: []
                    - id: c21a0472-6bef-4b44-aacc-aae307546d89
                      type: SCENARIO_MODIFIED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      comment: Added new processing step
                      additionalFields: []
                      overrideDisplayableName: Version 1 saved
                    - id: 4a6805de-6555-4976-92b2-9baefcccd990
                      type: SCENARIO_NAME_CHANGED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: oldName
                        value: marketing campaign
                      - name: newName
                        value: old marketing campaign
                    - id: cd1eb7b8-b266-44b3-983b-e4ba0cecb44b
                      type: COMMENT_ADDED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      comment: Now scenario handles errors in datasource better
                      additionalFields: []
                    - id: 552cf846-a330-46d8-a747-5884813ea6a3
                      type: COMMENT_ADDED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: deletedByUser
                        value: John Doe
                      overrideSupportedActions: []
                    - id: 12540601-f4d4-43ca-a303-a19baee30f8f
                      type: ATTACHMENT_ADDED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: attachmentId
                        value: '10000001'
                      - name: attachmentFilename
                        value: attachment01.png
                    - id: b350c1f4-0dda-4672-a525-23697fd58a2c
                      type: ATTACHMENT_ADDED
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: deletedByUser
                        value: John Doe
                      overrideSupportedActions: []
                    - id: 4de805c3-498d-4d51-837e-6931ba58f9fb
                      type: CHANGED_PROCESSING_MODE
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: from
                        value: Request-Response
                      - name: to
                        value: Request-Response
                    - id: adaa9335-6ca9-4afe-9791-0bb71375f6e8
                      type: INCOMING_MIGRATION
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      comment: Migration from preprod
                      additionalFields:
                      - name: sourceEnvironment
                        value: preprod
                      - name: sourceProcessVersionId
                        value: '23'
                    - id: 3dedd8bf-b3da-4d91-a3ea-a424a5248548
                      type: OUTGOING_MIGRATION
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      comment: Migration to preprod
                      additionalFields:
                      - name: destinationEnvironment
                        value: preprod
                    - id: 44a59921-c99b-4dcd-8ec3-06739c0825e3
                      type: PERFORMED_SINGLE_EXECUTION
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: dateFinished
                        value: '2024-01-17T14:21:17Z'
                      - name: status
                        value: Successfully executed
                    - id: f1bd6bc5-f624-4074-aa3d-072fda51331d
                      type: PERFORMED_SCHEDULED_EXECUTION
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: params
                        value: Batch size=1
                      - name: dateFinished
                        value: '2024-01-17T14:21:17Z'
                      - name: status
                        value: Successfully executed
                    - id: e4f55ffb-e595-417b-8586-2c2eee99d75e
                      type: AUTOMATIC_UPDATE
                      user: some user
                      date: '2024-01-17T14:21:17Z'
                      processVersionId: 1
                      additionalFields:
                      - name: changes
                        value: JIRA-12345, JIRA-32146
                      - name: dateFinished
                        value: '2024-01-17T14:21:17Z'
                      - name: status
                        value: Successful
        '400':
          description: 'Invalid value for: query parameter pageSize, Invalid value
            for: query parameter pageNumber, Invalid value for: query parameter activityType'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
  /api/processes/{scenarioName}/{versionId}/activity/comments:
    post:
      tags:
      - Comments
      summary: Add scenario comment service
      operationId: postApiProcessesScenarionameVersionidActivityComments
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: versionId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: path parameter versionId, Invalid value
            for: body'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
  /api/processes/{scenarioName}/activity/comments/{commentId}:
    put:
      tags:
      - Comments
      summary: Edit process comment service
      operationId: putApiProcessesScenarionameActivityCommentsCommentid
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: commentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: path parameter commentId, Invalid value
            for: body'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
        '500':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: 'Unable to edit comment with id: {commentId}'
                  value: 'Unable to delete comment with id: 1'
    delete:
      tags:
      - Comments
      summary: Delete process comment service
      operationId: deleteApiProcessesScenarionameActivityCommentsCommentid
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: commentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: path parameter commentId'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
        '500':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: 'Unable to edit comment with id: {commentId}'
                  value: 'Unable to delete comment with id: 1'
  /api/processes/{scenarioName}/activity/attachments:
    get:
      tags:
      - Attachments
      summary: Scenario attachments service
      operationId: getApiProcessesScenarionameActivityAttachments
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScenarioAttachments'
              examples:
                Example:
                  summary: Display scenario activity
                  value:
                    attachments:
                    - id: 1
                      processVersionId: 1
                      fileName: some_file.txt
                      user: test
                      createDate: '2024-01-17T14:21:17Z'
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
  /api/processes/{scenarioName}/{versionId}/activity/attachments:
    post:
      tags:
      - Attachments
      summary: Add scenario attachment service
      operationId: postApiProcessesScenarionameVersionidActivityAttachments
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: versionId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: Content-Disposition
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
        required: true
      responses:
        '200':
          description: ''
        '400':
          description: 'Invalid value for: path parameter versionId, Invalid value
            for: body, Invalid value for: header Content-Disposition'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
  /api/processes/{scenarioName}/activity/attachments/{attachmentId}:
    get:
      tags:
      - Attachments
      summary: Download attachment service
      operationId: getApiProcessesScenarionameActivityAttachmentsAttachmentid
      parameters:
      - name: scenarioName
        in: path
        required: true
        schema:
          type: string
      - name: attachmentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: ''
          headers:
            Content-Disposition:
              required: false
              schema:
                type:
                - string
                - 'null'
            Content-Type:
              required: true
              schema:
                type: string
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: 'Invalid value for: path parameter attachmentId'
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: ''
          content:
            text/plain:
              schema:
                type: string
              examples:
                Example:
                  summary: No scenario {scenarioName} found
                  value: No scenario 'example scenario' found
components:
  schemas:
    AdditionalField:
      title: AdditionalField
      type: object
      required:
      - name
      - value
      properties:
        name:
          type: string
        value:
          type: string
    Attachment:
      title: Attachment
      type: object
      required:
      - id
      - processVersionId
      - fileName
      - user
      - createDate
      properties:
        id:
          type: integer
          format: int64
        processVersionId:
          type: integer
          format: int64
        fileName:
          type: string
        user:
          type: string
        createDate:
          type: string
          format: date-time
    Comment:
      title: Comment
      type: object
      required:
      - id
      - processVersionId
      - content
      - user
      - createDate
      properties:
        id:
          type: integer
          format: int64
        processVersionId:
          type: integer
          format: int64
        content:
          type: string
        user:
          type: string
        createDate:
          type: string
          format: date-time
    FoundActivity:
      title: FoundActivity
      type: object
      required:
      - id
      - index
      properties:
        id:
          type: string
        index:
          type: integer
          format: int32
    ScenarioActivities:
      title: ScenarioActivities
      type: object
      properties:
        activities:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioActivity'
    ScenarioActivitiesCount:
      title: ScenarioActivitiesCount
      type: object
      required:
      - fullCount
      properties:
        fullCount:
          type: integer
          format: int64
    ScenarioActivitiesMetadata:
      title: ScenarioActivitiesMetadata
      type: object
      properties:
        activities:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioActivityMetadata'
        actions:
          type: array
          items:
            $ref: '#/components/schemas/ScenarioActivityActionMetadata'
    ScenarioActivitiesSearchResult:
      title: ScenarioActivitiesSearchResult
      type: object
      properties:
        foundActivities:
          type: array
          items:
            $ref: '#/components/schemas/FoundActivity'
    ScenarioActivity:
      title: ScenarioActivity
      type: object
      required:
      - id
      - type
      - user
      - date
      - processVersionId
      properties:
        id:
          type: string
        type:
          type: string
          enum:
          - SCENARIO_CREATED
          - SCENARIO_ARCHIVED
          - SCENARIO_UNARCHIVED
          - SCENARIO_DEPLOYED
          - SCENARIO_CANCELED
          - SCENARIO_MODIFIED
          - SCENARIO_NAME_CHANGED
          - COMMENT_ADDED
          - ATTACHMENT_ADDED
          - CHANGED_PROCESSING_MODE
          - INCOMING_MIGRATION
          - OUTGOING_MIGRATION
          - PERFORMED_SINGLE_EXECUTION
          - PERFORMED_SCHEDULED_EXECUTION
          - AUTOMATIC_UPDATE
        user:
          type: string
        date:
          type: string
          format: date-time
        processVersionId:
          type: integer
          format: int64
        comment:
          type:
          - string
          - 'null'
        additionalFields:
          type: array
          items:
            $ref: '#/components/schemas/AdditionalField'
        overrideDisplayableName:
          type:
          - string
          - 'null'
        overrideSupportedActions:
          type:
          - array
          - 'null'
          items:
            type: string
    ScenarioActivityActionMetadata:
      title: ScenarioActivityActionMetadata
      type: object
      required:
      - id
      - displayableName
      - icon
      properties:
        id:
          type: string
        displayableName:
          type: string
        icon:
          type: string
    ScenarioActivityMetadata:
      title: ScenarioActivityMetadata
      type: object
      required:
      - type
      - displayableName
      - icon
      properties:
        type:
          type: string
        displayableName:
          type: string
        icon:
          type: string
        supportedActions:
          type: array
          items:
            type: string
    ScenarioAttachments:
      title: ScenarioAttachments
      type: object
      properties:
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    ScenarioCommentsAndAttachments:
      title: ScenarioCommentsAndAttachments
      type: object
      properties:
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
